services:
  - type: web
    name: feldy-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements-build.txt && pip install -r requirements.txt
    startCommand: gunicorn app:app
